### ISSUE TITLE
Confuse DOC's on implementation.

### ISSUE THREAD

**Issue by ariefurtado** [appspector/android-sdk#11]
Hello,

I'm new on mobile development and the explanation how to **INITIALIZE APPSPECTOR SDK** is not obvious to me, srry guys XD

Can someone explain me where should I put the **INITIALIZE APPSPECTOR SDK** code?

It seems to me that I have to create a file, but... 

* where should I put this file?
* should I place all the code within the app level build.gradle?

Sorry for my noobness ^^

Thanks!

**Comment by Dimdron** [comment]
Hi @ariefurtado 
Usually, android project has 3 gradle files. 2 files are located in project root direcrory. These are `settings.gradle` and `build.gradle`
So, in this `build.gradle` you have to put [code](https://github.com/appspector/android-sdk#add-appspector-dependency-to-buildscript-in-your-project-level-buildgradle)
`buildscript {
  repositories {
      jcenter()
      google()
      maven {
          url "https://maven.appspector.com/artifactory/android-sdk"
      }
  }
  
  dependencies {
      classpath "com.appspector:android-sdk-plugin:1.+"
  }
}`

Also, project contains `app` folder (it may be named differently) with secound `build.gradle` and `src` folder. In secound `build.gradle` you have to put [code](https://github.com/appspector/android-sdk#modify-your-app-level-buildgradle):
`apply plugin: 'com.android.application'
// Put AppSpector plugin after Android plugin
apply plugin: 'com.appspector.sdk'

// Add AppSpector maven repository
repositories {
    maven {
        url "https://maven.appspector.com/artifactory/android-sdk"
    }
}

dependencies {
    implementation "com.appspector:android-sdk:1.+"
}`

**Comment by Dimdron** [comment]
And finally, you have to initialize AppSpector in your application class.
Here is example https://github.com/appspector/NewPipe

first gradle file https://github.com/appspector/NewPipe/blob/dev/build.gradle
secound one https://github.com/appspector/NewPipe/blob/dev/app/build.gradle
and application class https://github.com/appspector/NewPipe/blob/dev/app/src/debug/java/org/schabi/newpipe/DebugApp.java#L42

**Comment by ariefurtado** [comment]
Thanks a lot, now I am able to debug using AppSpector!!

But.... Can get any debugging on the Network Requests...

Do you have any clues?

PS: Everything seems to be working fine but the network requests.

**Comment by ariefurtado** [comment]
Here is my Initialization class!

`package com.unhideconference.app;

import android.app.Application;
import com.appspector.sdk.AppSpector;

public class UNHConferenceApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        AppSpector.build(this).addHttpMonitor().addEnvironmentMonitor().addScreenshotMonitor().addPerformanceMonitor()
                .addLocationMonitor().run("android_ZDk0NWZlOGUtYzFiOS00MzRjLWFiZTAtMmMxYTRhNWU5NzM2");
    }

}`

**Comment by ariefurtado** [comment]
Oh my!!!

I think i got the problem... 

![image](https://user-images.githubusercontent.com/8286080/63465522-ce9aaf00-c437-11e9-8956-b2d65a5073c4.png)

Since I'm using IONIC for development, and using Angular as a Front-end framework, I'm using a diferente think to make my HTTP Requests.

Is that correct?

If statemant is right, then I thing you can close this topic.

I hope this helps someone else.

**Comment by Dimdron** [comment]
Yeah, our SDK works only with OkHttp library

**Comment by Dimdron** [comment]
I guess it can be helpful for you https://www.charlesproxy.com

**Comment by sergeyzenchenko** [comment]
btw, @ariefurtado in future we are going to add support for HTTP requests from WebView.
