### ISSUE TITLE
Release version do not generate online session

### ISSUE THREAD

**Issue by damien-nd** [appspector/android-sdk#14]
I'm maybe not understanding the README, but:

In case when you don't want to have AppSpector SDK in your release APK use AppSpector NO-OP artifact

```
dependencies {
    debugImplementation "com.appspector:android-sdk:1.+"
    releaseImplementation "com.appspector:android-sdk-noop:1.+"
}
```

My understanding is that if I do not put this in my project, AppSpector should log in release Signed Bundle / APK?

If yes, it didn't work for me. I do create a private release and download it to my phone.
I can't see my session in online tabs but if I start a debug version with another phone, it is working fine.

Any ideas?

**Comment by Dimdron** [comment]
Hi, if you want to use AppSpector for `debug` and `release` flavors, you should put the next line:
`dependencies {
    implementation "com.appspector:android-sdk:1.+"
}`

NO-OP artifact is needed to exclude SDK logic without extra effort.
Also, for security purposes, we disable SDK if the application is installed from Play Store, etc.

**Comment by damien-nd** [comment]
I do have `implementation "com.appspector:android-sdk:1.1.5"` to avoid Android Studio warning but it should work the same?

**Comment by Dimdron** [comment]
Could you provide more details? What do you mean by "work the same"?
As I understood you, you've added only `com.appspector:android-sdk:1.1.5` dependency. 
In this case, release build which is not installed via Application Stores should create a session and produce data. Also, SDK writes a log with the `AppSpector` tag to Logcat.

**Comment by damien-nd** [comment]
If I download the app via Google Play Store (as a tester) it won't create session?

**Comment by Dimdron** [comment]
Nope. As I said in the first answer, for security purposes, we disable SDK for the same scenarios.
BUT now we are working on a new SDK version for production usage. It won't contain a real-time connection with the application and it'll propose some additional features. 😉

**Comment by damien-nd** [comment]
Sorry, I did read too fast and miss your last sentence. I'm ok to not have it in production for the moment, it is just simpler for me to distribute new app via Google Play Store for testing with other person. I will look to do it in another way, thank you.

**Comment by sarthak333** [comment]
@Dimdron As a growing startup, we chose AppSpector because we could look at the user's actions live to debug some of the hard-to-replicate issues. Are there any updates on the new SDK you mentioned in your previous comment? The one that could work for production usage?
