### ISSUE TITLE
Session doesn't start in Google Play Console's Internal testing build

### ISSUE THREAD

**Issue by dbogoslovtsev** [appspector/android-sdk#19]
Hi! We have used Firebase for a long time to test our .apks, but now we are moving to Firebase .aab testing, which uses Play Console's Internal testing to distribute builds. I saw in one of the closed issues that you don't allow starting sessions in applications from Play Market. 
Any suggestions/workarounds on this case? Our QA's are struggling since AppSpector stopped working.
Please let me know if you need any additional info

**Comment by Dimdron** [comment]
Hi! Thanks for the feedback!
Currently, we're working on SDK which allows debugging in the stores. It's in a closed beta state now however it should help you. Do you want to try it?

**Comment by Dimdron** [comment]
@dbogoslovtsev by the way, I recommend joining our slack)

**Comment by dbogoslovtsev** [comment]
Sure I'll gladly try the new version especially since the current one is non-working. Where can I get it?
Regarding the slack channel, I'd prefer not to have yet another muted space, I'd rather leave some of my existing spaces 😅 I'll join you if I have any further issues or questions, hope you understand 🙂

**Comment by dbogoslovtsev** [comment]
Actually, I've joined your space, we can move our discussion there

**Comment by Dimdron** [comment]
I've shared the migration guide. So the issue is closed. The next discussion will be on slack
