### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by szymonnn** [appspector/android-sdk#21]
Hi! 

In our project we are using the latest version of AppSpector SDK (1.4.3) and after upgrading some devices to Android 12 we stopped seeing sessions in AppSpector web app.

When we can expect support for Android 12? Are there any temporary workarounds that will allow us using AppSpector?

**Comment by Dimdron** [comment]
Hey, I hope it will be released today! Thanks for the feedback.

**Comment by Dimdron** [comment]
@szymonnn could you please try the latest version 1.4.4?

**Comment by Dimdron** [comment]
hey @szymonnn, any updates?

**Comment by szymonnn** [comment]
Hi, thanks for quick response. It's working properly :)
