### ISSUE TITLE
issue with appspector 1.4.4 and kotlin 1.4.x

### ISSUE THREAD

**Issue by taenguree** [appspector/android-sdk#22]
If I run appsepector 1.4.4 with kotlin 1.4.x, studio complain with below error. FYI) appsepctor 1.4.3 has no problem.

```
/Users/[USER]/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.1.
```

Suddenly, I saw this error today.

**Comment by Dimdron** [comment]
Hey, could you follow the next steps
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

**Comment by Dimdron** [comment]
hey @taenguree have you managed the compile issue?

**Comment by taenguree** [comment]
@Dimdron yes, I decided to use 1.4.3 version of appspector instead of 1.4.4 until I upgrade kotlin version 1.6.+
Thanks !

**Comment by Dimdron** [comment]
Gotcha. Thanks for info! The version 1.4.4 contains only compatibility fixes for SDK API 31. So, if you need to debug the app with Android S you can exclude the Kotlin dependencies or downgrade the version inside your app/build.gradle as mentioned in the article above.

**Comment by taenguree** [comment]
> Gotcha. Thanks for info! The version 1.4.4 contains only compatibility fixes for SDK API 31. So, if you need to debug the app with Android S you can exclude the Kotlin dependencies or downgrade the version inside your app/build.gradle as mentioned in the article above.
