### ISSUE TITLE
AppSpector not building

### ISSUE THREAD

**Issue by sourabhshegane** [appspector/android-sdk#23]
Getting the following error message
**_Could not GET 'https://dl.bintray.com/android/android-tools/com/appspector/android-sdk-plugin/maven-metadata.xml'. Received status code 502 from server: Bad Gateway_**

SDK version: 1.4.3

**Comment by Dimdron** [comment]
It's not our repository. Please, follow the README: https://github.com/appspector/android-sdk#add-appspector-dependency-to-buildscript-in-your-project-level-buildgradle
If it's already present try to move up the AppSpector repository in the declaration block

**Comment by sharvashish** [comment]
@Dimdron Even I am facing the same issue. Here is my gradle file dependencies:

repositories {
        jcenter()
        google()
        maven { url "https://maven.appspector.com/artifactory/android-sdk" }
        maven { url 'https://dl.bintray.com/android/android-tools' }
        mavenCentral()
}

I have tried changing the order but the error remains the same.

**Comment by Dimdron** [comment]
@sharvashish Have you done the same with repositories block inside buildscript?
