### ISSUE TITLE
Documentation for dependencies isn't clear

### ISSUE THREAD

**Issue by ColtonIdle** [appspector/android-sdk#6]
The buildscript, dependencies and plugins don't mention what file they should go in. Most libraries tell you to put x in your root build.gradle and y in your app level build.gradle. This increased the overhead of me installing and using AppSpector.

**Comment by sergeyzenchenko** [comment]
Thanks for feedback @ColtonIdle We'll update our docs to make it clear to understand.

**Comment by Dimdron** [comment]
I think the issue can be closed
