### ISSUE TITLE
Consider adding a no-op artifact

### ISSUE THREAD

**Issue by ColtonIdle** [appspector/android-sdk#7]
There are a lot of libraries that can be used for debugging and they typically have a no-op artifact so you can decide to leave out the library easily where you would like to.

An example of this is leak-canary:
```
  debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.6.3'
  releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.6.3'
```

**Comment by Dimdron** [comment]
@ColtonIdle We have no-op artifact but still didn't mention it in the documentation. We'll update docs soon 😉

**Comment by Dimdron** [comment]
@ColtonIdle we've updated our README

**Comment by Dimdron** [comment]
You can use noop artifact in this way:
```groovy
dependencies {
    debugImplementation "com.appspector:android-sdk:1.+"
    releaseImplementation "com.appspector:android-sdk-noop:1.+"
}
```
