### ISSUE TITLE
Couldn't create outDir

### ISSUE THREAD

**Issue by ColtonIdle** [appspector/android-sdk#8]
Running `./gradlew buildBetaDebug` on my Android app now shows this at the very end of the logs. Any idea?

```
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/43
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/176
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/94
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/42
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/106
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/60
Couldn't create outDir /Users/coltonidle/Android/Projects/busGoRound/app/build/intermediates/transforms/AppspectorSDKPlugin/beta/debug/181

... +200 more lines
```

This doesn't seem to actually break anything, but I figured I would flag it.

**Comment by Dimdron** [comment]
@ColtonIdle which version of AGP and Gradle do you use?

**Comment by ColtonIdle** [comment]
Using fairly latest versions IIRC. Let me check!

root build.gradle
`classpath 'com.android.tools.build:gradle:3.5.0-alpha07'`

gradle-wrapper.properties
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-all.zip`

**Comment by Dimdron** [comment]
I recommend using a stable plugin (currently, it's 3.3.2) because the alpha version has a lot of issues, etc.
However, if you need to use AGP v3.5.0, you can remove a AppSpector Gradle plugin and use OkHttpInterceptor: https://github.com/appspector/android-sdk#using-okhttp-interceptor-instead-of-appspector-gradle-plugin

**Comment by ColtonIdle** [comment]
Nope. Don't "need" to use it, it's just that AS is really slow on its stable release currently and they recommended moving to canary in order to get some of the fixes.

I mostly wanted to give your team a heads up.

Do you think there's any issue with those warnings, because everything with AppSpector seems to work fine.

**Comment by Dimdron** [comment]
So, as I see it's just a warnings and it doesn't affect our SDK. 
Thank you for report and sorry for the late response
